### ISSUE TITLE
Can pure JavaScript local packages be referenced by TS (i.e. mixed TS/JS MonoRepo)?

### ISSUE THREAD

**Issue by sixman9** [hanpama/typescript-composite-lerna#4]
I'm new to TypeScript (TS), but I *do* understand the overall concept of making TSC aware of where other local TypeScript project dependencies, with the MonoRepo. My question is, **is it possible to depend on pure JavaScript (JS, i.e. not-TS) local project/package dependencies and how would those be referenced, if being consumed by TS projects (and vice-versa)?**

I'm asking because I really do like the look of your MonoRepo solution for my projects, I just need to understand how I can integrate JS projects, if necessary.

**Comment by sixman9** [comment]
Might using TSC to 'compile' the JavaScript, by also including a `tsconfig.json` file to the JS project, be a possible solution (i.e. all packages, whether JS or TS have their own `tsconfig.json`)?

The following article details `tsconfig.json` usage with JavaScript.

- Detect JavaScript errors during compile time using TypeScript compiler
https://itnext.io/detect-javascript-errors-during-compile-time-using-typescript-compiler-be593b853c13

**Comment by hanpama** [comment]
@sixman9  Sorry for my late answer! I am not sure if this is still relevant for you.

* JavaScript module can import any module written in TypeScript because TypeScript just compiles into JS.
* TypeScript modules can use JavaScript modules by setting `tsconfig.json`'s `allowJs` option true.

Pure JS modules in a monorepo don't have to be linked in `tsconfig.json`. It only requires proper `package.json` `dependencies` settings.

If a local package is defined as a dependency of another local package, then Lerna will automatically build them in right order.
